### ISSUE TITLE
es-observable-tests?

### ISSUE THREAD

**Issue by ljharb** [zenparsing/zen-observable#1]
`package.json` doesn't mention it, and there's no github repo on https://www.npmjs.com/package/es-observable-tests - where is this code?

**Comment by zenparsing** [comment]
https://github.com/zenparsing/es-observable/tree/master/es-observable-tests

**Comment by nissoh** [comment]
@ljharb automatic build bundlers(wiredep in my case) will include anything within dependancies.

test files should be within devDependancies instead. i will include pr.
