### ISSUE TITLE
.then doesn't seem to work

### ISSUE THREAD

**Issue by marcoscaceres** [zenparsing/zen-observable#10]
Running the following example from the README, `then` seems to be missing or not implemented. 

```JS
Observable.of(0, 1, 2, 3, 4).reduce((previousValue, currentValue) => {
    return previousValue + currentValue;
}).then(result => {
    assert(result === 10);
});
```

**Comment by marcoscaceres** [comment]
Yields:

TypeError: Observable.of(...).reduce(...).then is not a function
    at Object.<anonymous> (/Users/marcos/Dropbox/repos/marcoscaceres/manifest-analytics/tlds/getTLD.js:33:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by zenparsing** [comment]
Oh, oops!

Thanks for pointing this out.  The library returns a new observable from "reduce", but at some point I was considering it returning a Promise.  I'm actually on the fence about which is the better option.  What do you think?

**Comment by RangerMauve** [comment]
Personally, I think that Reduce should be returning a promise, mostly because I found it nice to work with in [mostjs](https://github.com/cujojs/most/blob/master/docs/api.md#reduce). But [Rx](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/reduce.md) wouldn't agree so I'm not sure.

**Comment by zenparsing** [comment]
That's what reduce in Dart streams do as well, and it aligns better with the spirit of Array.prototype.reduce.

**Comment by marcoscaceres** [comment]
A promise might be good, in the sense that reduce is often a means to an ends:

const r = await o.filter(stuff).map(toThing).reduce(toSomething, new Collection());

Having said that, it could reduce to another observable... So can understand why this is a hard choice. 🤔

**Comment by marcoscaceres** [comment]
Ok, so, thinking about this more, and with the caveat that I've just started to play with Observables: I'm not sure about `.then()`... Thinking out loud here: the Observer abstraction is nice in that it allows you to react to a stream of events as they happen. But the streams consumed by an observable will not necessarily complete.

Putting .then() encourages `await`ing things that might never complete and I'm not sure that's a great use of them. Having said that, in #11 I use them to read a file in a way that's much nicer than creating a Transform stream - because I can filter out stuff, etc., in a more natural way. 

However, things get weird with .reduce()'ing into something that is not itself an Observable... because there you do need to wait for the stream to complete before you can use the result. Using .forEach() there feels a bit odd.

Again, I'm just thinking out loud here - and I'm sure other people have given this a lot of thought. I'll keep playing around.

**Comment by RangerMauve** [comment]
One thing to take into consideration is cancellation. Currently if you use a promise as the return, then that means your reduce will have to error out or resolve if you want things to behave properly. And if you no longer care about the result of the reduce, you'll have to kill an observable further up the chain. If reduce returns an observable which will emit a single value, you could just unsubscribe from it if you no longer cared about the computation.

**Comment by marcoscaceres** [comment]
@RangerMauve thanks for the clarification.

**Comment by zenparsing** [comment]
Fixed the README to indicate that an observable is returned.
