### ISSUE TITLE
Lua Port and License

### ISSUE THREAD

**Issue by tylorr** [zenparsing/zen-observable#12]
I'd like to make a port of this library to lua. If that is alright with you I'd like to know exactly how to include the license. Should I copy it verbatim or could I **add** a copyright of my own at the top? Such as:
`Port copyright (c) 2016 tylorr (Tylor Reynolds)`

**Comment by zenparsing** [comment]
I don't know exactly what the requirements are, but it doesn't matter to me.  Use it however you want!

**Comment by zenparsing** [comment]
Going to close this.  Happy porting!
