### ISSUE TITLE
Can you provide flow types

### ISSUE THREAD

**Issue by zerkalica** [zenparsing/zen-observable#13]
What about http://flowtype.org/ ?
Can you place .flowconfig  and flow-typed directory with type declarations?

**Comment by zenparsing** [comment]
Not at this time.

**Comment by n1ru4l** [comment]
@zenparsing are you open for a pull requests that adds flow type definitions?

**Comment by jedwards1211** [comment]
https://github.com/flow-typed/flow-typed/pull/3783
