### ISSUE TITLE
Document reliance on `this.constructor` and `Symbol.species` for subclassing?

### ISSUE THREAD

**Issue by isiahmeadows** [zenparsing/zen-observable#18]
I've noticed that for `.map` and friends, you rely on `this.constructor[Symbol.species]` or `this.constructor` to get the constructor, so you can support subclassing. This is understandable, but could this be documented? I'm using these to implement various `Subject`-like classes, and I'd rather not have to read the source to figure out how to properly subclass something.

**Comment by isiahmeadows** [comment]
I have already read the source myself to figure this out, but it would've been much easier to find that it works like this:

- Let `C` be `this.constructor[Symbol.species]` or `this.constructor`, whichever is a function first.
- Construct that with a single `subscriber` function argument.

It effectively expects the constructor found to accept the same arguments as the Observable constructor itself. Also, `Observable[Symbol.species]` is a non-standard property that, by default, a getter that returns `this`.

Just wishing this was actually documented as part of the public API.

**Comment by zenparsing** [comment]
It turns out that the species support was never fully implemented. It's now been fixed to match the usage of `@@species` of built-in classes. See #26 

Fixed in 0.5.1
