### ISSUE TITLE
Implementation of "scan"

### ISSUE THREAD

**Issue by daprahamian** [zenparsing/zen-observable#24]
How would I go about implementating [Rx's scan](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-scan)?

**Comment by zenparsing** [comment]
Taking the implementation of `reduce` here and modifying it, I think it would go like this:

```js
scan(fn) {

    if (typeof fn !== "function")
        throw new TypeError(fn + " is not a function");

    let C = getSpecies(this.constructor),
        hasSeed = arguments.length > 1,
        hasValue = false,
        seed = arguments[1],
        acc = seed;

    return new C(observer => this.subscribe({

        next(value) {

            if (observer.closed)
                return;

            let first = !hasValue;
            hasValue = true;

            if (!first || hasSeed) {

                try { acc = fn(acc, value) }
                catch (e) { return observer.error(e) }
                observer.next(acc);

            } else {

                acc = value;
            }
        },

        error(e) { observer.error(e) },
        complete() { observer.complete() },

    }));
}
```

**Comment by daprahamian** [comment]
Would it be possible to add this to the main library?

**Comment by zenparsing** [comment]
I'd like to keep the number of methods small and limited to what we find on Array. (Although `flatMap` is perhaps a strange exception.) Ideally, interesting combinators like `scan` could be implemented in a separate library via subclassing or [virtual methods](https://github.com/tc39/proposal-bind-operator).
