### ISSUE TITLE
TypeError: from(x) must be observable, iterable, or array-like: [object Object]

### ISSUE THREAD

**Issue by dumconstantin** [zenparsing/zen-observable#25]
Hi,

I've ran into this problem today and it took quite a long time to track down.

I'm using:
``` most: 1.2.2 ```
``` zen-observable: 0.4.0 ```
and running in node ``` 7.6.0 ```

The problem occurs because ``` zen-observable ``` relies on ``` Symbol['observable'] ``` to exist otherwise it will use ``` @@observable ``` instead.

``` mostjs ``` uses ``` symbol-observable ``` which will define ``` Symbol(observable) ``` if the ``` Symbol ``` function exist.

So if you create a ``` zen-observable ``` before including ``` most ```, then the observable will have ``` @@observable ``` instead of a Symbol and ``` most.from(observable) ``` will fail as a consequence.

Here's how to reproduce:
```
const Observable = require('zen-observable')
let observable = new Observable(observe => {})
const most = require('most')
most.from(observable)
// TypeError: from(x) must be observable, iterable, or array-like: [object Object]
````

While changing the order works:
```
const most = require('most')
const Observable = require('zen-observable')
let observable = new Observable(observe => {})
most.from(observable)
// works!
```

This really goes back to the decision in #9 .

I'm thinking changing ``` hasSymbol ``` and ``` getSymbol ``` to something along the lines of https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js might be a solution.

What do you think?

**Comment by zenparsing** [comment]
Sorry you had to spend debugging time on this; it should be fixed in https://github.com/zenparsing/zen-observable/commit/7cc5f2aa56a2ff07370dd2576a335bfe76bd056b. I'll update NPM later today.

**Comment by dumconstantin** [comment]
No worries. Thank you for the quick fix!

**Comment by zenparsing** [comment]
Updated npm version to 0.5.0. Let me know if you see any issues.

**Comment by dumconstantin** [comment]
Works! Thank you very much!
