### ISSUE TITLE
Complete shouldn't pass any value

### ISSUE THREAD

**Issue by softwarespot** [zenparsing/zen-observable#27]
Should complete be just this? As the specification states no value is passed through via the complete method.
`value = m ? m.call(observer) : undefined;`

**Source:** https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L198

**Comment by zenparsing** [comment]
This library is compliant with a previous version of the Observable specification that allowed the optional argument to `complete`. I still believe that this is the correct design and plan on leaving the implementation as-is for now. I'll revisit when or if Observable spec advances through the TC39 proposal process.
