### ISSUE TITLE
async function support

### ISSUE THREAD

**Issue by sebdeckers** [zenparsing/zen-observable#29]
Hey apologies for a newbie question. Are `async`/`await` functions supported by observables?

#### Reduced Example

```js
new Observable(async (observer) => {
  await (async () => {})
})
```

#### Error

```
TypeError: [object Promise] is not a function
    at Subscription (/Users/seb/Code/sebdeckers/http2live/node_modules/zen-observable/zen-observable.js:110:15)
    at Observable.subscribe (/Users/seb/Code/sebdeckers/http2live/node_modules/zen-observable/zen-observable.js:229:12)
    at Promise (/Users/seb/Code/sebdeckers/http2live/node_modules/listr/lib/task.js:132:13)
    at Promise (<anonymous>)
    at handleResult (/Users/seb/Code/sebdeckers/http2live/node_modules/listr/lib/task.js:131:14)
    at Promise.resolve.then.then.skipped (/Users/seb/Code/sebdeckers/http2live/node_modules/listr/lib/task.js:169:12)
    at <anonymous>
```

**Comment by zenparsing** [comment]
The low-level aspects of Observable are intentionally kept separate from promises. If you want to use `async/await` from within the subscriber function, you can do something like:

```js
new Observable(observer => {
  async function run() {
    observer.next(await someOperation());
  }
  run().then(() => observer.complete(), e => observer.error(e));
});
```

You will want to be careful to "abort" the async function if the observer has been unsubscribed, though.

You might also be interested in the [async generators](https://github.com/tc39/proposal-async-iteration/) proposal. We expect that when the language gets async generators, there will be some convenient way to convert from async iterators to Observables (for instance, with `Observable.from`).

**Comment by slorber** [comment]
Hi @zenparsing and thanks for your answer.

Does this generic util makes sense to you?

```
const promiseToObservable = <T extends any>(promise: Promise<T>) =>
  new Observable<T>(observer => {
    promise.then(
      t => {
        observer.next(t);
        observer.complete();
      },
      e => {
        observer.error(e);
      },
    );
  });
```

I'm handling the abortion part later in the flow btw

**Comment by slorber** [comment]
Ho nevermind, found exactly this in Apollo sourcecode here (using zen): https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/src/linkUtils.ts#L61
