### ISSUE TITLE
How to implement equivalent to RxJS's Subject

### ISSUE THREAD

**Issue by daprahamian** [zenparsing/zen-observable#36]
Hi,

What would be the best way to implement the equivalent to RxJS's `Subject`? I need to be able to push `next` notifications to multiple subscribers.

**Comment by zenparsing** [comment]
Here's one possibility: https://github.com/zenparsing/zen-push

**Comment by daprahamian** [comment]
awesome! Does that have type definitions for typescript?

**Comment by zenparsing** [comment]
It doesn't, but feel free to add an entry for `@types/zen-push` if you want to.

**Comment by daprahamian** [comment]
Ok, I guess that answers the question, so thanks!
