### ISSUE TITLE
Would you like to use a transpiler?

### ISSUE THREAD

**Issue by kof** [zenparsing/zen-observable#37]
I have it as a dev dependency an I see it failing in older browsers at least because of "let" statement. Would you like to support any browser?

**Comment by zenparsing** [comment]
It does use a transpiler. Requiring this package should bring in "zen-observable.js". I'm wondering if adding the "module" thing in package.json has messed things up for some people.

**Comment by kof** [comment]
checking…

**Comment by kof** [comment]
True, main property is correctly defined, it must by something else.

**Comment by kof** [comment]
I am using webpack 2.7.0

**Comment by zenparsing** [comment]
Yeah, I think that's what's going on. I've removed the "module" key from `package.json` and published a new NPM version `0.6.0`. Upgrade your dependency and see if that helps.

**Comment by kof** [comment]
works now, thanks a  lot!
