### ISSUE TITLE
.babelrc in npm

### ISSUE THREAD

**Issue by jiawang1** [zenparsing/zen-observable#45]
hi guys:

thanks for your great work, really like this simple and powerful library.  
I found an issue (maybe I think this is an issue). You put .babelrc file in npm.  If I want to compile packages from node_modules, your .babelrc will always has privilege and conflict with my plugins. now I have a workaround to get rid of this.
But I think .babelrc is unnessary in NPM. 

Regards

**Comment by zenparsing** [comment]
Thanks for this report!

The `babelrc` file has been removed in version `0.8.7`. Let me you know if you still see issues.

**Comment by jiawang1** [comment]
thanks for your support
