### ISSUE TITLE
bug in `combineLatest`

### ISSUE THREAD

**Issue by AngusFu** [zenparsing/zen-observable#46]
`combineLatest` can cause wrong order with its result.
This is caused by `Map`. 
`map.values()` will produce a MapIterator according to assigning orders.

```
values = new Map()
values.set(1, 1)
values.set(0, 0)
Array.from(values.values())  // [1, 0]
```

But running orders of oberservables are **uncertain**.

**Comment by dcosson** [comment]
Yes, the return line there should be something like `Array.from(values.entries()).sort((a, b) => a[0] - b[0]).map(([_, v]) => v)`.

Is this library maintained anymore?
