### ISSUE TITLE
can we mix up with rxjs operators?

### ISSUE THREAD

**Issue by veeramarni** [zenparsing/zen-observable#49]
I'm using `Apollo` which uses `zen-observables` and i would like to create a `apollo-link` package that does [buffer](http://reactivex.io/documentation/operators/buffer.html) operation, would it be fine to use the operator?

**Comment by kamilkisiela** [comment]
You can use `Apollo` with RxJS thanks to https://github.com/kamilkisiela/apollo-link-rxjs
