### ISSUE TITLE
Whitelist what files are published

### ISSUE THREAD

**Issue by jaydenseric** [zenparsing/zen-observable#56]
At the moment, a whole bunch of unnecessary files to do with source, tests, scripts, and dev tool config are published, which bloat `node_modules` when installed:

https://unpkg.com/zen-observable@0.8.13/

<img width="553" alt="screen shot 2019-01-30 at 10 29 42 am" src="https://user-images.githubusercontent.com/1754873/51947722-fca7aa00-2479-11e9-9493-ba11ea6e4ec2.png">

I suggest using the [package `files` field](https://docs.npmjs.com/files/package.json#files) to whitelist exactly what gets published.

**Comment by zenparsing** [comment]
Sticking with `.npmignore`.
