### ISSUE TITLE
Webpack build breaks

### ISSUE THREAD

**Issue by calebmer** [zenparsing/zen-observable#6]
Because the `require` keyword is present in `zen-observable.js` as a parameter, webpack tries to bundle all of the files in the root folder. Could the project be changed do maybe instead of calling the variable `require` instead call it `requireFn`? That way `require` can be used in the way which build tools like webpack expect.

**Comment by calebmer** [comment]
Turns out `require` is actually needed in a node environment, I thought it was just a syntax sugar thing. Because it's not used maybe `require` can just be removed entirely?

**Comment by zenparsing** [comment]
Thanks @calebmer, will take a look and get it working!

**Comment by zenparsing** [comment]
Should be fixed now in 0.1.8
