### ISSUE TITLE
TypeScript?

### ISSUE THREAD

**Issue by andywer** [zenparsing/zen-observable#60]
Hey @zenparsing!

I have been happily using `zen-observable` for at least two years now, most recently for [threads.js](https://github.com/andywer/threads.js). Sometimes I run into some subtle edge-casy issues with TypeScript, though.

Would you be interested in merging a TypeScript port of zen-observable? It shouldn't have any impact on the JS users, but would be pretty nice for all TS users.

**Comment by zenparsing** [comment]
One of these packages is probably the way to go:

* https://www.npmjs.com/package/zen-observable-ts
* https://www.npmjs.com/package/@types/zen-observable
