### ISSUE TITLE
Please add tags

### ISSUE THREAD

**Issue by guimard** [zenparsing/zen-observable#61]
Hello,

to help packaging, could you add tags corresponding to npm releases ?

Cheers,
Xavier (Debian packager)

**Comment by zenparsing** [comment]
I created a tag for the most recent version. Is that sufficient or do you want tags farther back?

**Comment by guimard** [comment]
Yes, thank you !

**Comment by guimard** [comment]
Please don't forget to add tags for the next versions

**Comment by guimard** [comment]
Hi, tag 0.8.15 is missing

**Comment by zenparsing** [comment]
Added.

**Comment by guimard** [comment]
Thanks, 0.8.15 uploaded to [Debian unstable](https://tracker.debian.org/pkg/node-zen-observable) _(will appear in a few minutes)_
