### ISSUE TITLE
Exporting as ES Module Syntax (ESM)

### ISSUE THREAD

**Issue by abdonrd** [zenparsing/zen-observable#62]
Please, export `"module"` entry point in the `package.json` as ES Module Syntax (ESM).

More info about it here: https://www.pikapkg.com/about/

**Comment by zenparsing** [comment]
We added a `module` key in the past, but unfortunately this caused problems for some users.

https://github.com/zenparsing/zen-observable/issues/37

It seems that "fixing" things for one set of tools tends to break other tools. We also tried supporting `.mjs` for a while and that caused issues as well. Things may have changed in the ecosystem, though.

What is the practical benefit here? So that it can be indexed by pika?

**Comment by abdonrd** [comment]
With a proposal like this #64, the idea is to export the package in two formats:
* Common.js format as `dist-cjs/Observable.js` (same as the current export)
* ES Modules format as `dist/Observable.js`

The benefit is that importing the library becomes much easier in cases such as:
* Load in the browser with any tool. All major browsers can load standard ES Modules now.
* Load in bundlers like Rollup.

About the `.mjs` extension, was just a experimental proposal from Node.js.
But finally seems that the ES Modules implementation from Node.js will use just `.js`.

The link to Pika was just a reference to the ES module syntax.

**Comment by zenparsing** [comment]
Based on past experience, I'm still worried that supporting both module systems at the same time will cause issues for existing libraries. Can you give a concrete example of how *not* supporting both module systems is causing issues?

**Comment by abdonrd** [comment]
Try to use it directly in the browser, without tools. You can't use the standard ES Modules.

Example: https://glitch.com/edit/#!/cheddar-girdle

If you import the `index.js` you get an error:
>Uncaught SyntaxError: The requested module 'https://unpkg.com/zen-observable/index.js' does not provide an export named 'default'

(I made the example work using importing the `src/Observable.js`)

**Comment by abdonrd** [comment]
My final goal is use `apollo-client` directly in the browser as ES Modules. And `apollo-client` already export as ES Modules, but it has a couple of depedencies (`zen-observable` is one of them) that don't.

Then I get the error:
>Uncaught SyntaxError: The requested module '...' does not provide an export named 'default'

---

And I have an example using `apollo-client` direclty in the browser with the #64 PR:
https://github.com/abdonrd/open-wc-application-apollo-client/compare/master...apollo-client-es-modules#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22

**Comment by abdonrd** [comment]
Maybe the bad experience of the past was for not [defining this in the `package.json`](https://github.com/zenparsing/zen-observable/pull/64/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R8-R9)?

```json
  "main": "lib/cjs/index.js",
  "module": "lib/index.js",
```

**Comment by zenparsing** [comment]
What is throwing this error:

`Uncaught SyntaxError: The requested module '...' does not provide an export named 'default'`

Is that rollup, or the browser, or something else?

**Comment by abdonrd** [comment]
This error is from the browser:

>Uncaught SyntaxError: The requested module '...' does not provide an export named 'default'

**Comment by zenparsing** [comment]
In order to use a library like `apollo-client` (that has dependencies) directly on the web, don't you need to either bundle up the dependencies or use an import map?

**Comment by abdonrd** [comment]
If you want to see it, just remove this line and run the application:

https://github.com/abdonrd/open-wc-application-apollo-client/compare/apollo-client-es-modules#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22

**Comment by abdonrd** [comment]
No, it is not necessary. You can test the application running without any build/bundled here:

https://github.com/abdonrd/open-wc-application-apollo-client/compare/apollo-client-es-modules

We only do the build & bundled to optimize the application in production. But not during local development.

**Comment by zenparsing** [comment]
Sounds cool - I'll give it a try.

**Comment by abdonrd** [comment]
Great! Thank you @zenparsing!

**Comment by abdonrd** [comment]
There are any news @zenparsing? Thanks in advance!

**Comment by zenparsing** [comment]
This is a tough one. I tried to run the app but wasn't able to get it working (with the few minutes I had).

Node 13 will support ESM without a flag using `"type": "module"`  in package.json, but it [won't support dual-mode packages](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_compatibility_with_commonjs_only_versions_of_node_js) (where both ESM and CJS can be used for the same package at the same time). Given this direction, and the experiences I've had in the past with "module" and ".mjs", I'm still hesitant.

For now, I've added a better esm entry point at  [zen-observable/esm.js](https://github.com/zenparsing/zen-observable/blob/master/esm.js). For your use case, is there any way that you can tell the browser to look there for the package entry point?

**Comment by abdonrd** [comment]
As far as I know, the only way is to use the `module`/`main` fields, which is what tools usually understand as ES Modules. If you just add this to the `package.json`, what stops working?

```
  "main": "index.js",
  "module": "esm.js",
```

**Comment by abdonrd** [comment]
And there are other big packages like Redux using this `module`/`main` fields:

https://github.com/reduxjs/redux/blob/c2973f480bc4e5b6bf7d42a714d4790311cd1a26/package.json#L26-L28

**Comment by semmel** [comment]
@zenparsing Please push `0.8.15` on npm. 
`esm.js` just solves my problem importing zen-observable! Thank you! 👍

**Comment by abdonrd** [comment]
There are any news @zenparsing? Thanks in advance!

**Comment by Splaktar** [comment]
I am running into this same issue with an app built using `apollo-client`. It gives this error with Angular CLI version 10:
```
WARNING in /Users/splaktar/Git/my-app/node_modules/zen-observable-ts/lib/bundle.esm.js depends on 'zen-observable'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
https://angular.io/guide/build#configuring-commonjs-dependencies has some good links to explain why CommonJS modules don't support tree shaking and how ES Modules work.

`zen-observable-ts` is importing correctly:
```ts
import zenObservable from 'zen-observable';
```
But due to the lacking `"module": "esm.js"`, that ends up getting the CommonJS module (`index.js`) instead of the ES Module.

**Comment by nikita-lobkov** [comment]
Any updates on this? Looks PR is still not merged yet :C

**Comment by bendehghan** [comment]
any update on this??

**Comment by zenparsing** [comment]
Will be addressed in https://github.com/zenparsing/zen-observable/pull/86
