### ISSUE TITLE
Ambiguous error showing up in Firefox (but not Chrome)

### ISSUE THREAD

**Issue by ffxsam** [zenparsing/zen-observable#65]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/12532733/68258847-aa457c00-fffd-11e9-81a4-94dc6c4c76ed.png">

Sorry I don't have more info than this. A third party npm package is using zen-observable, and this is all I can get as far as a stack trace.

**Comment by zenparsing** [comment]
Interesting - thanks for the report!

Are you able to edit the zen-observable sources? You might be able to find them in `node_modules/zen-observable/lib/Observable.js`. If you can find it, you can edit the `hostReportErrors` function to throw immediately:

```js
function hostReportError(e) {
  throw e; // <--- Add this line
  if (hostReportError.log) {
    hostReportError.log(e);
  } else {
    setTimeout(() => { throw e });
  }
}
```

That might give you a better stack trace.

**Comment by ffxsam** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/12532733/68480954-9c5d4a00-01fb-11ea-9782-08847258070e.png">

So there's a more fleshed-out stack trace. I'm using AWS AppSync (a GraphQL client) that uses MQTT (and hence websockets) for real-time data. I realized the error only happens when I hit reload, which means it's breaking the WS connection and causing this error to be thrown. It may have more to do with AppSync than this package, I'm starting to think.

**Comment by zenparsing** [comment]
Closing as stale.
