### ISSUE TITLE
Async notification / discrepancy with tc39 implementation

### ISSUE THREAD

**Issue by dy** [zenparsing/zen-observable#67]
Consider state observable:

```js
import Observable from "zen-observable";

let state = { foo: "foo" };
let o = new Observable(observer => {
  observer.next(state);
});
o.subscribe(state => console.log(state.foo));
state.foo = "bar";
```
([sandbox](https://codesandbox.io/s/muddy-river-49l4t?fontsize=14&hidenavigation=1&theme=dark))

The `es-observable` logs 'foo' to console, the `zen-observable` logs `bar`, because notification is asynchronous.
Is there a particular reason for `Promise.resolve()` [here](https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L53)?

**Comment by zenparsing** [comment]
This was a point of debate during the proposal development process. The idea behind the approach in `zen-observable` is that (similar to the Promise API), callers of `subscribe` will generally assume that values will not be delivered *during* the call to `subscribe`.

Thanks for the question!
