### ISSUE TITLE
shared multicast implementation?

### ISSUE THREAD

**Issue by jedwards1211** [zenparsing/zen-observable#72]
As I mentioned in https://github.com/tc39/proposal-observable/issues/66#issuecomment-601533902, without a single agreed-upon multicast implementation, multiple libraries that need multicast in their own internal observables might have redundant implementations that bloat a browser bundle.

Obviously I could make a centralized multicast implementation in separate package, but then *someone else might do so too* without finding about my package, and we would still have the same problem.  So I think this package is really the best place for a multicast implementation to live.  Would you be interested in a PR?

**Comment by zenparsing** [comment]
@jedwards1211 I'd prefer to leave this library very basic, and have another package that does the multicasting thing. I'm going to update https://github.com/zenparsing/zen-push, so maybe I'll put a nice API there.

https://github.com/zenparsing/zen-push/issues/4
