### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by yairopro** [zenparsing/zen-observable#81]
Since there's no "discussions" tab for this project, I ask the question here.

Why zen-observable? 
What's the difference with RxJS?

The readme says

> An implementation of Observables for JavaScript

Where is the definition of Observables (outside RxJS)?

And last but not the least.. why **zen**? 🧘🏻‍♂️

**Comment by roitalpaz** [comment]
I'm also asking why, and why apollo decided to use this library?

**Comment by andersonmadeira** [comment]
Well, I do know the answer to one of those questions:

>
> Where is the definition of Observables (outside RxJS)?
> 

It is actually an ES proposal: 
https://github.com/tc39/proposal-observable.

**Comment by zenparsing** [comment]
> And last but not the least.. why zen? 🧘🏻‍♂️

Why not?
