### ISSUE TITLE
Please stop polyfilling `Symbol.observable` 🙏

### ISSUE THREAD

**Issue by jorroll** [zenparsing/zen-observable#87]
I don't use `zen-observable` directly, but I do import Apollo client which imports this library.  Somewhat unexpectedly, this library polyfills `Symbol.observable` here: https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L6-L8

This polyfill is breaking my code because, suddenly, the order of execution of modules accessing `Symbol.observable` matters. I'll need to add `import "zen-observable"` to the polyfill section of my code 😆.  Even though it is a breaking change, it would be _**fantastic**_ if `zen-observable` followed the pattern of other libraries accessing `Symbol.observable` in a non-side effecting manner.

E.g. (from rxjs)

```ts
export const observableSymbol: string | symbol = (() => (typeof Symbol === 'function' && Symbol.observable) || '@@observable')();
```

I think many developers would find the bugs caused by the current behavior just about impossible to diagnose, but since I'm mildly familiar with rxjs internals and have written some custom `from()` functions before, I got lucky and figured out what was going on.

**Comment by jorroll** [comment]
Actually it looks like you already grab SymbolObservable in a non-side-effecting way [here](https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L11) 
`const SymbolObservable = getSymbol('observable');`

So maybe all that's needed is to delete the polyfill. I guess you could move it into a separate, optional package entry point. But it's also not clear that it's still needed. The ecosystem seems to have standardized on using the string `@@observable` until (and if) `Symbol.observable` is formally added to browsers.

**Comment by zenparsing** [comment]
Polyfill has been removed in `0.10.0`. Dependents will need to be updated in order to resolve polyfill-ordering issues.

**Comment by azza666666azza-hue** [comment]
> I don't use `zen-observable` directly, but I do import Apollo client which imports this library.  Somewhat unexpectedly, this library polyfills `Symbol.observable` here: https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L6-L8
> 
> 
> 
> This polyfill is breaking my code because, suddenly, the order of execution of modules accessing `Symbol.observable` matters. I'll need to add `import "zen-observable"` to the polyfill section of my code 😆.  Even though it is a breaking change, it would be _**fantastic**_ if `zen-observable` followed the pattern of other libraries accessing `Symbol.observable` in a non-side effecting manner.
> 
> 
> 
> E.g. (from rxjs)
> 
> 
> 
> ```ts
> 
> export const observableSymbol: string | symbol = (() => (typeof Symbol === 'function' && Symbol.observable) || '@@observable')();
> 
> ```
> 
> 
> 
> I think many developers would find the bugs caused by the current behavior just about impossible to diagnose, but since I'm mildly familiar with rxjs internals and have written some custom `from()` functions before, I got lucky and figured out what was going on.
> 
> 

🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻🖕🏻
